---
- name: Install Node Exporter on EC2 Instance
  hosts: all
  gather_facts: True
  become: yes

  tasks:
    - name: Install necessary dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - tar

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_os_arch }}.tar.gz"
        dest: /tmp/node_exporter.tar.gz
        mode: '0644'
      vars:
        node_exporter_version: "1.2.2"
        node_exporter_os_arch: "{{ ansible_system | lower }}-{{ 'amd64' if ansible_architecture == 'x86_64' else '386' }}"

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt
        remote_src: yes
        extra_opts: --strip-components=1
        creates: /opt/node_exporter

    - name: Configure Node Exporter service
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start Node Exporter service
      service:
        name: node_exporter
        state: started
        enabled: yes
